### PR TITLE
Add all previous primers

### PR DESCRIPTION
**Pull request by ChampionAsh5357**
Adds all previous primers into `primers/<release_version>/` `index.md` is used for vanilla changes while `<mod_loader>.md` is used for changes within the specified mod loader.

### CODE REVIEW

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]
Add an README.md under the `primers` subdirectory linking to each file, for ease of access.

All of the primers are CC BY 4.0 International according to their introductory text, which differs from the repository's general license, so please add licensing info to that README and the full legal text of the license in a `LICENSE` file (mirroring `art/LICENSE`).

The files should be lightly edited due to the change from a gist to a repository file: instead of "leaving a comment below", it should either ask to file an issue or ask in the official Discord server.

**Comment by ChampionAsh5357** [comment]
Should the copyright remain under me or should it be under the neoforged team?

**Comment by sciwhiz12** [comment]
Err. It'd depend on you, I suppose, though if you do assign the copyright to the NeoForged team, I would then recommend you add credits for yourself as the original authors of the primers.

**Comment by ChampionAsh5357** [comment]
For right now then, I'll keep the copyright. If I need to transfer it at a later point, I can write up something to that degree.

**Comment by sciwhiz12** [comment]
Actually, just realized: add the credit for yourself as the original author anyway, copyright re-assigned or not.

**Review by sciwhiz12 — APPROVED** [review]

**Pull request merged**
