### PR TITLE
Moving Big Change gists to .github repo

### PR DESCRIPTION
**Pull request by TelepathicGrunt**
Converting these Gists to this repo: 
https://gist.github.com/TelepathicGrunt/4de77c67adb661c9380e594d20b6a58b

Folder name and file name is up for debate. Leave feedback please. I am thinking a file per major MC version might work?

### CODE REVIEW

**Review by sciwhiz12 — COMMENTED** [review]
The proposed folder structure has me curious what else do we plan to store in this folder. Do we plan on adding new changes summaries documents for each Minecraft version?

Also, why not use periods in the folder name instead of dashes?

**Comment by TelepathicGrunt** [comment]
@sciwhiz12 I figured breaking up the changes doc per major mc versions would make sense for organization tbh. I can do periods for the folder name too yeah. This was just me throwing something at the wall to see what sticks. Could be a big_change folder and the files be like 1_21_x.md or something

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]
The authorship and copyright of these files need to be clarified. As I understand it, you wrote these files (with some help from the community). 

Please add a README.md to the `changes` folder giving an overview of what the documents are, linking to the two extant documents, crediting yourself as author, and noting the license of the documents if any. (Otherwise, the documents will be covered by the Unlicense in the root of the repository.)

Also, given that we are probably not going to have more than one file per version in this directory tree (since we're likely to have separate trees for different docs: see the primers for example), perhaps we could streamline it to `technical_changes/1.21.md` and so on?

**Review by sciwhiz12 — APPROVED** [review]
Good enough for me. 😄

**Pull request merged**
